# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170309_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='location',
        ),
    ]
